apiVersion: "config.istio.io/v1alpha2"
kind: denier
metadata:
  name: denyall
spec:
  status:
    code: 7
    message: Not allowed
---
# The (empty) data handed to denyall at run time
apiVersion: "config.istio.io/v1alpha2"
kind: checknothing
metadata:
  name: denyrequest
spec:
---
# The rule that uses denier to deny requests to the guestbook service
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: deny-guestbook
spec:
  match: destination.service.name=="guestbook"
  actions:
  - handler: denyall.denier
    instances:
    - denyrequest.checknothing
